# 1. Import dependencies

In [ ]:
%pip install scikit-learn

In [1]:
import numpy as np
import pandas as pd

import sklearn

# 2. Working with Date & DateTime

1. International Standard Formats
    
   SO 8601: The global standard for date and time representation.
   
     * `YYYY-MM-DD` (e.g., 2026-03-26).
     * `YYYY-MM-DDTHH:mm:ss.sssZ` (e.g., 2026-03-26T12:29:00.000Z).
        
    RFC 2822 / RFC 1123: Used primarily in HTTP headers and email.
        
     * `ddd, DD MMM YYYY HH:mm:ss GMT` (e.g., Thu, 26 Mar 2026 12:29:00 GMT). 

2. Common Regional Formats
Formats vary significantly by country and culture: 

    US (MDY): `MM/DD/YYYY` (e.g., 03/26/2026).

    Europe/UK (DMY): `DD/MM/YYYY` (e.g., 26/03/2026).
   
    China/Japan/Korea (YMD): `YYYY/MM/DD` (e.g., 2026/03/26). 

3. Custom Format Tokens
Programming languages use specific "tokens" to build custom date strings: 

    Year: `yy` (2-digit), `yyyy` (4-digit).

    Month: `M` (1-digit), `MM` (2-digit), `MMM` (short name), `MMMM`(full name).
   
    Day: `d` (1-digit), `dd` (2-digit), `ddd` (short weekday), `dddd` (full weekday).
   
    Time: `HH` (24-hour), `hh` (12-hour), `mm` (minutes), `ss` (seconds), a or `tt` (AM/PM). 

4. Language-Specific Methods

    JavaScript: Use native methods like `toISOString()` for standards or `toLocaleDateString()` for local formats.
   
    Python: Use `strftime()` to define explicit formats like `"%Y-%m-%d %H:%M:%S"`.
   
    Java: Use the DateTimeFormatter class to parse and format strings.
   
    .NET: Supports Standard Format Strings (e.g., "d" for short date) and Custom Format Strings (e.g., `"yyyy-MM-dd"`).

In [12]:
df = pd.read_csv("./src/Turbine_Data.csv")[["TimeStamp",]]

df.head()

                   TimeStamp
0  2017-12-31 00:00:00+00:00
1  2017-12-31 00:10:00+00:00
2  2017-12-31 00:20:00+00:00
3  2017-12-31 00:30:00+00:00
4  2017-12-31 00:40:00+00:00

In [13]:
df.dtypes

TimeStamp    object
dtype: object

In [14]:
df["TimeStamp_datetime"] = pd.to_datetime(df["TimeStamp"])
df.head()

                   TimeStamp        TimeStamp_datetime
0  2017-12-31 00:00:00+00:00 2017-12-31 00:00:00+00:00
1  2017-12-31 00:10:00+00:00 2017-12-31 00:10:00+00:00
2  2017-12-31 00:20:00+00:00 2017-12-31 00:20:00+00:00
3  2017-12-31 00:30:00+00:00 2017-12-31 00:30:00+00:00
4  2017-12-31 00:40:00+00:00 2017-12-31 00:40:00+00:00

In [15]:
df.dtypes

TimeStamp                          object
TimeStamp_datetime    datetime64[ns, UTC]
dtype: object

In [17]:
df["TimeStamp_date"] = df["TimeStamp_datetime"].dt.date
df.head()

                   TimeStamp        TimeStamp_datetime TimeStamp_date
0  2017-12-31 00:00:00+00:00 2017-12-31 00:00:00+00:00     2017-12-31
1  2017-12-31 00:10:00+00:00 2017-12-31 00:10:00+00:00     2017-12-31
2  2017-12-31 00:20:00+00:00 2017-12-31 00:20:00+00:00     2017-12-31
3  2017-12-31 00:30:00+00:00 2017-12-31 00:30:00+00:00     2017-12-31
4  2017-12-31 00:40:00+00:00 2017-12-31 00:40:00+00:00     2017-12-31

In [18]:
df.dtypes

TimeStamp                          object
TimeStamp_datetime    datetime64[ns, UTC]
TimeStamp_date                     object
dtype: object

In [19]:
df["TimeStamp_time"] = df["TimeStamp_datetime"].dt.time
df.head()

,TimeStamp,TimeStamp_datetime,TimeStamp_date,TimeStamp_time
0,2017-12-31 00:00:00+00:00,2017-12-31 00:00:00+00:00,2017-12-31,00:00:00
1,2017-12-31 00:10:00+00:00,2017-12-31 00:10:00+00:00,2017-12-31,00:10:00
2,2017-12-31 00:20:00+00:00,2017-12-31 00:20:00+00:00,2017-12-31,00:20:00
3,2017-12-31 00:30:00+00:00,2017-12-31 00:30:00+00:00,2017-12-31,00:30:00
4,2017-12-31 00:40:00+00:00,2017-12-31 00:40:00+00:00,2017-12-31,00:40:00

In [20]:
df.dtypes

TimeStamp                          object
TimeStamp_datetime    datetime64[ns, UTC]
TimeStamp_date                     object
TimeStamp_time                     object
dtype: object

In [21]:
df["TimeStamp_year"] = df["TimeStamp_datetime"].dt.year
df.head()

,TimeStamp,TimeStamp_datetime,TimeStamp_date,TimeStamp_time,TimeStamp_year
0,2017-12-31 00:00:00+00:00,2017-12-31 00:00:00+00:00,2017-12-31,00:00:00,2017
1,2017-12-31 00:10:00+00:00,2017-12-31 00:10:00+00:00,2017-12-31,00:10:00,2017
2,2017-12-31 00:20:00+00:00,2017-12-31 00:20:00+00:00,2017-12-31,00:20:00,2017
3,2017-12-31 00:30:00+00:00,2017-12-31 00:30:00+00:00,2017-12-31,00:30:00,2017
4,2017-12-31 00:40:00+00:00,2017-12-31 00:40:00+00:00,2017-12-31,00:40:00,2017

In [22]:
df["TimeStamp_month"] = df["TimeStamp_datetime"].dt.month
df.head()

,TimeStamp,TimeStamp_datetime,TimeStamp_date,TimeStamp_time,TimeStamp_year,TimeStamp_month
0,2017-12-31 00:00:00+00:00,2017-12-31 00:00:00+00:00,2017-12-31,00:00:00,2017,12
1,2017-12-31 00:10:00+00:00,2017-12-31 00:10:00+00:00,2017-12-31,00:10:00,2017,12
2,2017-12-31 00:20:00+00:00,2017-12-31 00:20:00+00:00,2017-12-31,00:20:00,2017,12
3,2017-12-31 00:30:00+00:00,2017-12-31 00:30:00+00:00,2017-12-31,00:30:00,2017,12
4,2017-12-31 00:40:00+00:00,2017-12-31 00:40:00+00:00,2017-12-31,00:40:00,2017,12

In [32]:
df["TimeStamp_day"] = df["TimeStamp_datetime"].dt.month
df.head()

,TimeStamp,TimeStamp_datetime,TimeStamp_date,TimeStamp_time,TimeStamp_year,TimeStamp_month,TimeStamp_hour,Duration_year,TimeStamp_day
0,2017-12-31 00:00:00+00:00,2017-12-31 00:00:00+00:00,2017-12-31,00:00:00,2017,12,0,8.232717,12
1,2017-12-31 00:10:00+00:00,2017-12-31 00:10:00+00:00,2017-12-31,00:10:00,2017,12,0,8.232717,12
2,2017-12-31 00:20:00+00:00,2017-12-31 00:20:00+00:00,2017-12-31,00:20:00,2017,12,0,8.232717,12
3,2017-12-31 00:30:00+00:00,2017-12-31 00:30:00+00:00,2017-12-31,00:30:00,2017,12,0,8.232717,12
4,2017-12-31 00:40:00+00:00,2017-12-31 00:40:00+00:00,2017-12-31,00:40:00,2017,12,0,8.232717,12

In [23]:
df["TimeStamp_hour"] = df["TimeStamp_datetime"].dt.hour
df.head()

,TimeStamp,TimeStamp_datetime,TimeStamp_date,TimeStamp_time,TimeStamp_year,TimeStamp_month,TimeStamp_hour
0,2017-12-31 00:00:00+00:00,2017-12-31 00:00:00+00:00,2017-12-31,00:00:00,2017,12,0
1,2017-12-31 00:10:00+00:00,2017-12-31 00:10:00+00:00,2017-12-31,00:10:00,2017,12,0
2,2017-12-31 00:20:00+00:00,2017-12-31 00:20:00+00:00,2017-12-31,00:20:00,2017,12,0
3,2017-12-31 00:30:00+00:00,2017-12-31 00:30:00+00:00,2017-12-31,00:30:00,2017,12,0
4,2017-12-31 00:40:00+00:00,2017-12-31 00:40:00+00:00,2017-12-31,00:40:00,2017,12,0

In [24]:
today_ts = pd.Timestamp.today()
today_ts

Timestamp('2026-03-26 12:46:11.276229')

In [28]:
df["Duration_year"] = (today_ts - df["TimeStamp_datetime"].dt.tz_localize(None)).dt.days / 365.25
df.head()

,TimeStamp,TimeStamp_datetime,TimeStamp_date,TimeStamp_time,TimeStamp_year,TimeStamp_month,TimeStamp_hour,Duration_year
0,2017-12-31 00:00:00+00:00,2017-12-31 00:00:00+00:00,2017-12-31,00:00:00,2017,12,0,8.232717
1,2017-12-31 00:10:00+00:00,2017-12-31 00:10:00+00:00,2017-12-31,00:10:00,2017,12,0,8.232717
2,2017-12-31 00:20:00+00:00,2017-12-31 00:20:00+00:00,2017-12-31,00:20:00,2017,12,0,8.232717
3,2017-12-31 00:30:00+00:00,2017-12-31 00:30:00+00:00,2017-12-31,00:30:00,2017,12,0,8.232717
4,2017-12-31 00:40:00+00:00,2017-12-31 00:40:00+00:00,2017-12-31,00:40:00,2017,12,0,8.232717

In [35]:
df["Assembled_date"] = df['TimeStamp_year'].astype(str) + "_" + df['TimeStamp_day'].astype(str) + "_" + df['TimeStamp_month'].astype(str)
df.head()

,TimeStamp,TimeStamp_datetime,TimeStamp_date,TimeStamp_time,TimeStamp_year,TimeStamp_month,TimeStamp_hour,Duration_year,TimeStamp_day,Assembled_date
0,2017-12-31 00:00:00+00:00,2017-12-31 00:00:00+00:00,2017-12-31,00:00:00,2017,12,0,8.232717,12,2017_12_12
1,2017-12-31 00:10:00+00:00,2017-12-31 00:10:00+00:00,2017-12-31,00:10:00,2017,12,0,8.232717,12,2017_12_12
2,2017-12-31 00:20:00+00:00,2017-12-31 00:20:00+00:00,2017-12-31,00:20:00,2017,12,0,8.232717,12,2017_12_12
3,2017-12-31 00:30:00+00:00,2017-12-31 00:30:00+00:00,2017-12-31,00:30:00,2017,12,0,8.232717,12,2017_12_12
4,2017-12-31 00:40:00+00:00,2017-12-31 00:40:00+00:00,2017-12-31,00:40:00,2017,12,0,8.232717,12,2017_12_12

In [37]:
df["Assembled_datetime"] = pd.to_datetime(df["Assembled_date"], format="%Y_%d_%m")
df.head()

,TimeStamp,TimeStamp_datetime,TimeStamp_date,TimeStamp_time,TimeStamp_year,TimeStamp_month,TimeStamp_hour,Duration_year,TimeStamp_day,Assembled_date,Assembled_datetime
0,2017-12-31 00:00:00+00:00,2017-12-31 00:00:00+00:00,2017-12-31,00:00:00,2017,12,0,8.232717,12,2017_12_12,2017-12-12
1,2017-12-31 00:10:00+00:00,2017-12-31 00:10:00+00:00,2017-12-31,00:10:00,2017,12,0,8.232717,12,2017_12_12,2017-12-12
2,2017-12-31 00:20:00+00:00,2017-12-31 00:20:00+00:00,2017-12-31,00:20:00,2017,12,0,8.232717,12,2017_12_12,2017-12-12
3,2017-12-31 00:30:00+00:00,2017-12-31 00:30:00+00:00,2017-12-31,00:30:00,2017,12,0,8.232717,12,2017_12_12,2017-12-12
4,2017-12-31 00:40:00+00:00,2017-12-31 00:40:00+00:00,2017-12-31,00:40:00,2017,12,0,8.232717,12,2017_12_12,2017-12-12

In [38]:
df.tail()

,TimeStamp,TimeStamp_datetime,TimeStamp_date,TimeStamp_time,TimeStamp_year,TimeStamp_month,TimeStamp_hour,Duration_year,TimeStamp_day,Assembled_date,Assembled_datetime
118219,2020-03-30 23:10:00+00:00,2020-03-30 23:10:00+00:00,2020-03-30,23:10:00,2020,3,23,5.984942,3,2020_3_3,2020-03-03
118220,2020-03-30 23:20:00+00:00,2020-03-30 23:20:00+00:00,2020-03-30,23:20:00,2020,3,23,5.984942,3,2020_3_3,2020-03-03
118221,2020-03-30 23:30:00+00:00,2020-03-30 23:30:00+00:00,2020-03-30,23:30:00,2020,3,23,5.984942,3,2020_3_3,2020-03-03
118222,2020-03-30 23:40:00+00:00,2020-03-30 23:40:00+00:00,2020-03-30,23:40:00,2020,3,23,5.984942,3,2020_3_3,2020-03-03
118223,2020-03-30 23:50:00+00:00,2020-03-30 23:50:00+00:00,2020-03-30,23:50:00,2020,3,23,5.984942,3,2020_3_3,2020-03-03

# 3. Categorical data (boolean)

Presentations of such data:

* `Y` & `N`
* `T` & `F`
* `True` & `False`
* `A` & `B`

In [39]:
df = pd.DataFrame({
    "BinCol": ["Y", "N", "Y", "Y", "Y", "N"]
})
df.head(6)

  BinCol
0      Y
1      N
2      Y
3      Y
4      Y
5      N

In [41]:
df["BinCol"].value_counts()

BinCol
Y    4
N    2
Name: count, dtype: int64

In [44]:
df["BinCol_Bool"] = df["BinCol"] == "Y"
df.head()

  BinCol  BinCol_Bool
0      Y         True
1      N        False
2      Y         True
3      Y         True
4      Y         True

In [45]:
df["BinCol_Int"] = (df["BinCol"] == "Y").astype(int)
df.head()

  BinCol  BinCol_Bool  BinCol_Int
0      Y         True           1
1      N        False           0
2      Y         True           1
3      Y         True           1
4      Y         True           1

In [46]:
df["BinCol_MapValue"] = df["BinCol"].map(lambda x: 1 if x == "Y" else -1)
df.head()

  BinCol  BinCol_Bool  BinCol_Int  BinCol_MapValue
0      Y         True           1                1
1      N        False           0               -1
2      Y         True           1                1
3      Y         True           1                1
4      Y         True           1                1

In [47]:
df["BinCol_MapValueDict"] = df["BinCol"].map({"Y": 1, "N": -1})
df.head()

  BinCol  BinCol_Bool  BinCol_Int  BinCol_MapValue  BinCol_MapValueDict
0      Y         True           1                1                    1
1      N        False           0               -1                   -1
2      Y         True           1                1                    1
3      Y         True           1                1                    1
4      Y         True           1                1                    1

In [48]:
df.dtypes

BinCol                 object
BinCol_Bool              bool
BinCol_Int              int64
BinCol_MapValue         int64
BinCol_MapValueDict     int64
dtype: object

# 4. Purely Categorical Data
## 4.1. Ordered

In [50]:
df = pd.DataFrame({
    "hardness": ["very soft", "very soft", "hard", "hard", "very hard", "medium", "soft"],
})

df.head(10)

    hardness
0  very soft
1  very soft
2       hard
3       hard
4  very hard
5     medium
6       soft

In [51]:
df["hardness"] > "medium"

0     True
1     True
2    False
3    False
4     True
5    False
6     True
Name: hardness, dtype: bool

In [53]:
hardness = {
    "very soft": 1,
    "soft": 2,
    "medium": 3,
    "hard": 4,
    "very hard": 5,
}

df["hardness_num"] = df["hardness"].map(hardness)
df.head(10)

    hardness  hardness_num
0  very soft             1
1  very soft             1
2       hard             4
3       hard             4
4  very hard             5
5     medium             3
6       soft             2

In [54]:
df["hardness_num"] > hardness["medium"]

0    False
1    False
2     True
3     True
4     True
5    False
6    False
Name: hardness_num, dtype: bool

## 4.2. Non-ordered

* One-hot encoding
* Dummy encoding
* Ordinal encoding (for ordered categories)
* Binary encoding
* Count Encoding
* Target Encoding

### 4.3.1. One-hot encoding for binary data (with True/False, T/F, Y/N, Yes/No, ...)

In [2]:
df = pd.DataFrame({
    "bin_cat": [True, False, True, False, False, True, True, True, True],
})
df.head()

   bin_cat
0     True
1    False
2     True
3    False
4    False

In [3]:
df["bin_cat"] = df["bin_cat"].astype(int)
df.head()

   bin_cat
0        1
1        0
2        1
3        0
4        0

In [5]:
# if missing value in bin cat data

df = pd.DataFrame({
    "bin_cat": [True, False, None, True, False, None, False, True, True, True, True],
})
df

   bin_cat
0     True
1    False
2     None
3     True
4    False
5     None
6    False
7     True
8     True
9     True
10    True

### 4.3.2. One-hot encoding for categorical data with multiple categories

In [6]:
# example of purely categorical data
df = pd.read_csv(
    "../homeworks_2025_2026/pr_3/src/titanic_surv_data.csv",
    usecols=["PassengerId", "Embarked"]
)
df.head()

   PassengerId Embarked
0          892        Q
1          893        S
2          894        Q
3          895        S
4          896        S

In [7]:
df["Embarked"].value_counts()

Embarked
S    270
C    102
Q     46
Name: count, dtype: int64

In [12]:
pd.get_dummies(df, columns=["Embarked"], prefix_sep="__")

     PassengerId  Embarked__C  Embarked__Q  Embarked__S
0            892        False         True        False
1            893        False        False         True
2            894        False         True        False
3            895        False        False         True
4            896        False        False         True
..           ...          ...          ...          ...
413         1305        False        False         True
414         1306         True        False        False
415         1307        False        False         True
416         1308        False        False         True
417         1309         True        False        False

[418 rows x 4 columns]

In [13]:
pd.get_dummies(df, columns=["Embarked"], prefix_sep="__", dtype="int")

     PassengerId  Embarked__C  Embarked__Q  Embarked__S
0            892            0            1            0
1            893            0            0            1
2            894            0            1            0
3            895            0            0            1
4            896            0            0            1
..           ...          ...          ...          ...
413         1305            0            0            1
414         1306            1            0            0
415         1307            0            0            1
416         1308            0            0            1
417         1309            1            0            0

[418 rows x 4 columns]

In [20]:
from sklearn.preprocessing import OneHotEncoder

oh_encoder = OneHotEncoder(sparse_output=False)
oh_encoder.fit_transform(df[["Embarked"]])

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.]], shape=(418, 3))

In [21]:
oh_encoder.transform(df[["Embarked"]])

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.]], shape=(418, 3))

In [25]:
oh_encoder.categories_

[array(['C', 'Q', 'S'], dtype=object)]

In [27]:
oh_encoder.get_feature_names_out()

array(['Embarked_C', 'Embarked_Q', 'Embarked_S'], dtype=object)

In [28]:
oh_encoder.get_metadata_routing()

{}

In [24]:
from sklearn.preprocessing import LabelEncoder

lab_enc = LabelEncoder()
lab_enc.fit_transform(df["Embarked"])

array([1, 2, 1, 2, 2, 2, 1, 2, 0, 2, 2, 2, 2, 2, 2, 0, 1, 0, 2, 0, 0, 2,
       2, 0, 0, 2, 0, 0, 2, 0, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 0, 1, 0, 2, 2, 0, 2, 2, 0, 1, 2, 2, 2, 0, 2, 2, 2, 1, 0, 2,
       1, 2, 0, 2, 1, 2, 2, 0, 0, 0, 2, 2, 2, 1, 0, 2, 2, 2, 1, 0, 1, 2,
       1, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 1, 2, 0, 2, 1, 1, 2, 2,
       0, 1, 0, 1, 2, 0, 0, 2, 0, 2, 2, 1, 0, 2, 1, 2, 2, 1, 2, 2, 2, 0,
       2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 0, 2, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 0, 2, 2,
       2, 0, 2, 0, 2, 0, 2, 1, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2,
       2, 2, 1, 2, 0, 2, 2, 0, 1, 2, 0, 2, 2, 2, 2, 2, 2, 2, 1, 2, 0, 2,
       0, 2, 2, 2, 0, 0, 2, 1, 2, 2, 2, 2, 2, 1, 0, 2, 0, 0, 2, 0, 0, 2,
       0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2,
       0, 2, 2, 2, 2, 2, 0, 1, 0, 1, 0, 2, 2, 2, 2, 2, 2, 2, 1, 0, 2, 2,
       2, 2, 0, 2, 2, 1, 0, 2, 2, 2, 0, 0, 2, 2, 2, 0, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 0, 2, 1, 0, 1, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2,
       2, 0, 0, 0, 2, 2, 2, 0, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2, 2, 0, 2, 0, 2, 0, 0, 2, 0, 2, 2,
       2, 0, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2,
       1, 0, 2, 1, 2, 2, 0, 2, 0, 0, 2, 0, 1, 2, 1, 1, 2, 2, 0, 2, 2, 0])

### 4.3.3. Count (Frequency) Encoding

In [29]:
%pip install feature_engine

Collecting feature_engine
  Downloading feature_engine-1.9.4-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy>=1.18.2 in d:\documents\python_projects\datamining\.venv\lib\site-packages (from feature_engine) (2.2.3)
Requirement already satisfied: pandas>=2.2.0 in d:\documents\python_projects\datamining\.venv\lib\site-packages (from feature_engine) (2.2.3)
Requirement already satisfied: scikit-learn>=1.4.0 in d:\documents\python_projects\datamining\.venv\lib\site-packages (from feature_engine) (1.6.1)
Requirement already satisfied: scipy>=1.4.1 in d:\documents\python_projects\datamining\.venv\lib\site-packages (from feature_engine) (1.15.2)
Collecting statsmodels>=0.11.1 (from feature_engine)
  Downloading statsmodels-0.14.6-cp311-cp311-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\documents\python_projects\datamining\.venv\lib\site-packages (from pandas>=2.2.0->feature_engine) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\documents\python_projects\datamining\.venv\lib\site-packages (from pandas>=2.2.0->feature_engine) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in d:\documents\python_projects\datamining\.venv\lib\site-packages (from pandas>=2.2.0->feature_engine) (2025.1)
Requirement already satisfied: joblib>=1.2.0 in d:\documents\python_projects\datamining\.venv\lib\site-packages (from scikit-learn>=1.4.0->feature_engine) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in d:\documents\python_projects\datamining\.venv\lib\site-packages (from scikit-learn>=1.4.0->feature_engine) (3.6.0)
Collecting patsy>=0.5.6 (from statsmodels>=0.11.1->feature_engine)
  Downloading patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: packaging>=21.3 in d:\documents\python_projects\datamining\.venv\lib\site-packages (from statsmodels>=0.11.1->feature_engine) (24.2)
Requirement already satisfied: six>=1.5 in d:\documents\python_projects\datamining\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->feature_engine) (1.17.0)
Downloading feature_engine-1.9.4-py3-none-any.whl (243 kB)
Downloading statsmodels-0.14.6-cp311-cp311-win_amd64.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.6 MB 3.4 MB/s eta 0:00:03
   ----- ---------------------------------- 1.3/9.6 MB 3.9 MB/s eta 0:00:03
   --------- ------------------------------ 2.4/9.6 MB 3.8 MB/s eta 0:00:02
   ------------- -------------------------- 3.1/9.6 MB 4.0 MB/s eta 0:00:02
   ----------------- ---------------------- 4.2/9.6 MB 4.1 MB/s eta 0:00:02
   -------------------- ------------------- 5.0/9.6 MB 4.1 MB/s eta 0:00:02
   ------------------------- -------------- 6.0/9.6 MB 4.2 MB/s eta 0:00:01
   ----------------------------- ---------- 7.1/9.6 MB 4.3 MB/s eta 0:00:01
   -------------------------------- ------- 7.9/9.6 MB 4.2 MB/s eta 0:00:01
   ------------------------------------- -- 8.9/9.6 MB 4.3 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.6 MB 4.2 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.6 MB 4.2 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.6 MB 4.2 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.6 MB 4.2 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.6 MB 4.2 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.6 MB 4.2 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.6 MB 4.2 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.6 MB 4.2 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.6 MB 4.2 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.6 MB 4.2 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.6 MB 4.2 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.6 MB 4.2 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.6 MB 4.2 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.6 MB 4.2 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.6 MB 4.2 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.6 MB 4.2 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.6 MB 4.2 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.6 MB 4.2 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.6 MB 4.2 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.6 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.6 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------- 9.6/9.6 MB 1.5 MB/s eta 0:00:00
Downloading patsy-1.0.2-py2.py3-none-any.whl (233 kB)
Installing collected packages: patsy, statsmodels, feature_engine
Successfully installed feature_engine-1.9.4 patsy-1.0.2 statsmodels-0.14.6
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [30]:
from feature_engine.encoding import CountFrequencyEncoder

In [31]:
df = pd.read_csv(
    "../homeworks_2025_2026/pr_3/src/titanic_surv_data.csv",
    usecols=["PassengerId", "Name", "Sex", "Embarked"]
)
df.head()

   PassengerId                                          Name     Sex Embarked
0          892                              Kelly, Mr. James    male        Q
1          893              Wilkes, Mrs. James (Ellen Needs)  female        S
2          894                     Myles, Mr. Thomas Francis    male        Q
3          895                              Wirz, Mr. Albert    male        S
4          896  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female        S

In [32]:
encoder = CountFrequencyEncoder(
    encoding_method='count',
    variables=['Name', 'Sex', 'Embarked'],
)

encoder.fit(df)

CountFrequencyEncoder(variables=['Name', 'Sex', 'Embarked'])

In [33]:
encoder.encoder_dict_

{'Name': {'Peter, Master. Michael J': 1,
  'Kelly, Mr. James': 1,
  'Gale, Mr. Harry': 1,
  'Bonnell, Miss. Caroline': 1,
  'Conlon, Mr. Thomas Henry': 1,
  'Larsson-Rondberg, Mr. Edvard A': 1,
  'Frolicher-Stehli, Mrs. Maxmillian (Margaretha Emerentia Stehli)': 1,
  'Colbert, Mr. Patrick': 1,
  'Smith, Mrs. Lucien Philip (Mary Eloise Hughes)': 1,
  'Kink-Heilmann, Mr. Anton': 1,
  'Gilbert, Mr. William': 1,
  'Abbott, Master. Eugene Joseph': 1,
  'Lines, Mrs. Ernest H (Elizabeth Lindsey James)': 1,
  'Payne, Mr. Vivian Ponsonby': 1,
  'Palsson, Master. Paul Folke': 1,
  'Canavan, Mr. Patrick': 1,
  'Ashby, Mr. John': 1,
  'Aronsson, Mr. Ernst Axel Algot': 1,
  'Johnston, Mrs. Andrew G (Elizabeth Lily" Watson)"': 1,
  'Dean, Mrs. Bertram (Eva Georgetta Light)': 1,
  'Jefferys, Mr. Clifford Thomas': 1,
  'Louch, Mr. Charles Alexander': 1,
  'Samaan, Mr. Elias': 1,
  'Brady, Mr. John Bertram': 1,
  'Daher, Mr. Shedid': 1,
  'Ostby, Miss. Helene Ragnhild': 1,
  'Robins, Mr. Alexander A': 1,
  'Ryerson, Mrs. Arthur Larned (Emily Maria Borie)': 1,
  'Williams, Mr. Richard Norris II': 1,
  'Flegenheim, Mrs. Alfred (Antoinette)': 1,
  'Olsen, Master. Artur Karl': 1,
  'Rothschild, Mr. Martin': 1,
  'Assaf Khalil, Mrs. Mariana (Miriam")"': 1,
  'Ilmakangas, Miss. Ida Livija': 1,
  'Coutts, Mrs. William (Winnie Minnie" Treanor)"': 1,
  'Bucknell, Mrs. William Robert (Emma Eliza Ward)': 1,
  'Shaughnessy, Mr. Patrick': 1,
  'Chevre, Mr. Paul Romaine': 1,
  'Peltomaki, Mr. Nikolai Johannes': 1,
  'Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons)': 1,
  'Corbett, Mrs. Walter H (Irene Colvin)': 1,
  'Goldsmith, Mr. Nathan': 1,
  'Franklin, Mr. Thomas Parham': 1,
  'Karun, Mr. Franz': 1,
  'Hee, Mr. Ling': 1,
  'Sap, Mr. Julius': 1,
  'Cacic, Miss. Manda': 1,
  'Roth, Miss. Sarah A': 1,
  'Katavelas, Mr. Vassilios (Catavelas Vassilios")"': 1,
  'Mock, Mr. Philipp Edmund': 1,
  'Corey, Mrs. Percy C (Mary Phyllis Elizabeth Miller)': 1,
  'Ryerson, Master. John Borie': 1,
  'Bradley, Miss. Bridget Delia': 1,
  'Bjorklund, Mr. Ernst Herbert': 1,
  'McCrae, Mr. Arthur Gordon': 1,
  'Dika, Mr. Mirko': 1,
  'Chaudanson, Miss. Victorine': 1,
  'Davison, Mr. Thomas Henry': 1,
  'Abelseth, Mr. Olaus Jorgensen': 1,
  'Cor, Mr. Bartol': 1,
  'Rice, Master. Albert': 1,
  'Mangiavacchi, Mr. Serafino Emilio': 1,
  'Fortune, Miss. Ethel Flora': 1,
  'Hocking, Miss. Ellen Nellie""': 1,
  'Pulbaum, Mr. Franz': 1,
  'Smith, Mr. Lucien Philip': 1,
  'Straus, Mr. Isidor': 1,
  'Boulos, Master. Akar': 1,
  'Doyle, Miss. Elizabeth': 1,
  'Aldworth, Mr. Charles Augustus': 1,
  'Cornell, Mrs. Robert Clifford (Malvina Helen Lamson)': 1,
  'Miles, Mr. Frank': 1,
  'Keeping, Mr. Edwin': 1,
  'Geiger, Miss. Amalie': 1,
  'Ovies y Rodriguez, Mr. Servando': 1,
  'Nieminen, Miss. Manta Josefina': 1,
  'Minkoff, Mr. Lazar': 1,
  'Mulvihill, Miss. Bertha E': 1,
  'Fortune, Mrs. Mark (Mary McDougald)': 1,
  'Tucker, Mr. Gilbert Milligan Jr': 1,
  'Moore, Mr. Clarence Bloomfield': 1,
  'Burns, Miss. Mary Delia': 1,
  'Makinen, Mr. Kalle Edvard': 1,
  'Cavendish, Mrs. Tyrell William (Julia Florence Siegel)': 1,
  'Tenglin, Mr. Gunnar Isidor': 1,
  'Birnbaum, Mr. Jakob': 1,
  'Guest, Mr. Robert': 1,
  'Davidson, Mrs. Thornton (Orian Hays)': 1,
  'Pedersen, Mr. Olaf': 1,
  'Dyker, Mrs. Adolf Fredrik (Anna Elisabeth Judith Andersson)': 1,
  'Wells, Master. Ralph Lester': 1,
  "O'Donoghue, Ms. Bridget": 1,
  'Badman, Miss. Emily Louisa': 1,
  'Barry, Miss. Julia': 1,
  'Khalil, Mr. Betros': 1,
  'Lamb, Mr. John Joseph': 1,
  'Demetri, Mr. Marinko': 1,
  'Case, Mr. Howard Brown': 1,
  'Buckley, Miss. Katherine': 1,
  'Evans, Miss. Edith Corse': 1,
  'Shine, Miss. Ellen Natalia': 1,
  'Stanton, Mr. Samuel Ward': 1,
  'Swane, Mr. George': 1,
  'Willer, Mr. Aaron (Abi Weller")"': 1,
  'Ryan, Mr. Edward': 1,
  'Buckley, Mr. Daniel': 1,
  'Holthen, Mr. Johan Martin': 1,
  'Thomas, Mrs. Alexander (Thamine Thelma")"': 1,
  'Johansson Palmquist, Mr. Oskar Leander': 1,
  'Foley, Mr. William': 1,
  'Weisz, Mr. Leopold': 1,
  'Stengel, Mrs. Charles Emil Henry (Annie May Morris)': 1,
  'Nancarrow, Mr. William Henry': 1,
  'Braf, Miss. Elin Ester Maria': 1,
  'Petersen, Mr. Marius': 1,
  'Bowenur, Mr. Solomon': 1,
  'McCoy, Miss. Alicia': 1,
  'Brobeck, Mr. Karl Rudolf': 1,
  'Cribb, Miss. Laura Alice': 1,
  'Kennedy, Mr. John': 1,
  'Carver, Mr. Alfred John': 1,
  'Schabert, Mrs. Paul (Emma Mock)': 1,
  'Kiernan, Mr. John': 1,
  'Watt, Miss. Bertha J': 1,
  'Chapman, Mrs. John Henry (Sara Elizabeth Lawry)': 1,
  'Beattie, Mr. Thomson': 1,
  'Sandstrom, Miss. Beatrice Irene': 1,
  'Thomas, Mr. John': 1,
  'Chronopoulos, Mr. Demetrios': 1,
  'Straus, Mrs. Isidor (Rosalie Ida Blun)': 1,
  'Vander Planke, Mr. Julius': 1,
  'Lindeberg-Lind, Mr. Erik Gustaf (Mr Edward Lingrey")"': 1,
  'Beauchamp, Mr. Henry James': 1,
  'Ryerson, Mr. Arthur Larned': 1,
  'Daniels, Miss. Sarah': 1,
  'Goodwin, Miss. Jessie Allis': 1,
  'Goodwin, Mr. Charles Frederick': 1,
  'Drapkin, Miss. Jennie': 1,
  'Schmidt, Mr. August': 1,
  'Zakarian, Mr. Mapriededer': 1,
  'Carlsson, Mr. Carl Robert': 1,
  'Dintcheff, Mr. Valtcho': 1,
  'Thomas, Mr. Charles P': 1,
  'Lefebre, Mrs. Frank (Frances)': 1,
  'Gracie, Col. Archibald IV': 1,
  'Spinner, Mr. Henry John': 1,
  'Touma, Master. Georges Youssef': 1,
  'Smyth, Miss. Julia': 1,
  'Peacock, Mrs. Benjamin (Edith Nile)': 1,
  'Borebank, Mr. John James': 1,
  'Lundin, Miss. Olga Elida': 1,
  'Bird, Miss. Ellen': 1,
  'Duquemin, Mr. Joseph': 1,
  'Asplund, Master. Filip Oscar': 1,
  'Klasen, Mrs. (Hulda Kristina Eugenia Lofqvist)': 1,
  'Storey, Mr. Thomas': 1,
  'Matinoff, Mr. Nicola': 1,
  'Earnshaw, Mrs. Boulton (Olive Potter)': 1,
  'Lahtinen, Rev. William': 1,
  'Crafton, Mr. John Bertram': 1,
  'Davies, Mr. Evan': 1,
  'Hilliard, Mr. Herbert Henry': 1,
  'Stengel, Mr. Charles Emil Henry': 1,
  'Sincock, Miss. Maude': 1,
  'Brown, Miss. Edith Eileen': 1,
  'Asplund, Mr. Carl Oscar Vilhelm Gustafsson': 1,
  'Torfa, Mr. Assad': 1,
  'Dyker, Mr. Adolf Fredrik': 1,
  'Zakarian, Mr. Ortin': 1,
  'Lithman, Mr. Simon': 1,
  'Hellstrom, Miss. Hilda Maria': 1,
  'Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genevieve Fosdick)': 1,
  'Ford, Mr. Edward Watson': 1,
  'Brandeis, Mr. Emil': 1,
  'Kink-Heilmann, Mrs. Anton (Luise Heilmann)': 1,
  'Peruschitz, Rev. Joseph Maria': 1,
  'Pearce, Mr. Ernest': 1,
  'Wright, Miss. Marion': 1,
  'Lingane, Mr. John': 1,
  'van Billiard, Master. Walter John': 1,
  'Salomon, Mr. Abraham L': 1,
  'Angle, Mr. William A': 1,
  'Veal, Mr. James': 1,
  'Sage, Miss. Ada': 1,
  'Davies, Mr. Joseph': 1,
  'Phillips, Miss. Alice Frances Louisa': 1,
  'Maybery, Mr. Frank Hubert': 1,
  'Douglas, Mrs. Frederick Charles (Mary Helene Baxter)': 1,
  'Lane, Mr. Patrick': 1,
  'Marvin, Mrs. Daniel Warner (Mary Graham Carmichael Farquarson)': 1,
  'Compton, Mr. Alexander Taylor Jr': 1,
  'McCrie, Mr. James Matthew': 1,
  'Compton, Mrs. Alexander Taylor (Mary Eliza Ingersoll)': 1,
  'Becker, Mrs. Allen Oliver (Nellie E Baumgardner)': 1,
  'Delalic, Mr. Redjo': 1,
  'Rosenbaum, Miss. Edith Louise': 1,
  'Collett, Mr. Sidney C Stuart': 1,
  'McGowan, Miss. Katherine': 1,
  'Omont, Mr. Alfred Fernand': 1,
  'Andrew, Mr. Frank Thomas': 1,
  'Quick, Miss. Winifred Vera': 1,
  'Astor, Col. John Jacob': 1,
  'Danbom, Master. Gilbert Sigvard Emanuel': 1,
  'Murphy, Miss. Nora': 1,
  'Rasmussen, Mrs. (Lena Jacobsen Solvang)': 1,
  'Baimbrigge, Mr. Charles Robert': 1,
  'Nilsson, Miss. Berta Olivia': 1,
  'Spedden, Master. Robert Douglas': 1,
  'Karlsson, Mr. Julius Konrad Eugen': 1,
  'Drew, Master. Marshall Brines': 1,
  'Moubarek, Mrs. George (Omine Amenia" Alexander)"': 1,
  'Candee, Mrs. Edward (Helen Churchill Hungerford)': 1,
  'Karlsson, Mr. Einar Gervasius': 1,
  'Cook, Mrs. (Selena Rogers)': 1,
  'Reynolds, Mr. Harold J': 1,
  'Duran y More, Miss. Florentina': 1,
  'Thomson, Mr. Alexander Morrison': 1,
  'Widener, Mrs. George Dunton (Eleanor Elkins)': 1,
  'Wick, Mr. George Dennick': 1,
  'Mahon, Miss. Bridget Delia': 1,
  'Head, Mr. Christopher': 1,
  'Andersson, Miss. Ida Augusta Margareta': 1,
  'Howard, Mrs. Benjamin (Ellen Truelove Arman)': 1,
  'Deacon, Mr. Percy William': 1,
  'Finoli, Mr. Luigi': 1,
  'Andersen, Mr. Albert Karvin': 1,
  'Christy, Mrs. (Alice Frances)': 1,
  'Lindstrom, Mrs. Carl Johan (Sigrid Posse)': 1,
  'Douglas, Mrs. Walter Donald (Mahala Dutton)': 1,
  'Hiltunen, Miss. Marta': 1,
  'Baccos, Mr. Raffull': 1,
  'Warren, Mr. Frank Manley': 1,
  'Vendel, Mr. Olof Edvin': 1,
  'Cumings, Mr. John Bradley': 1,
  'Linehan, Mr. Michael': 1,
  'Wiklund, Mr. Karl Johan': 1,
  'Willard, Miss. Constance': 1,
  'Sweet, Mr. George Frederick': 1,
  'Hocking, Mr. Samuel James Metcalfe': 1,
  'Everett, Mr. Thomas James': 1,
  'McNeill, Miss. Bridget': 1,
  'Asplund, Mr. Johan Charles': 1,
  'Niklasson, Mr. Samuel': 1,
  'Mahon, Mr. John': 1,
  'MacKay, Mr. George William': 1,
  'Wenzel, Mr. Linhart': 1,
  'Salander, Mr. Karl Johan': 1,
  'Clark, Mr. Walter Miller': 1,
  'Abrahamsson, Mr. Abraham August Johannes': 1,
  'West, Miss. Barbara J': 1,
  'Khalil, Mrs. Betros (Zahie Maria" Elias)"': 1,
  'Hold, Mrs. Stephen (Annie Margaret Hill)': 1,
  'Drew, Mr. James Vivian': 1,
  'Karnes, Mrs. J Frank (Claire Bennett)': 1,
  'Kenyon, Mr. Frederick R': 1,
  'Johnston, Master. William Arthur Willie""': 1,
  'Hyman, Mr. Abraham': 1,
  'Spedden, Mr. Frederic Oakley': 1,
  'Lennon, Miss. Mary': 1,
  'Clark, Mrs. Walter Miller (Virginia McDowell)': 1,
  'Fox, Mr. Patrick': 1,
  'McCaffry, Mr. Thomas Francis': 1,
  'Pokrnic, Mr. Mate': 1,
  'Howard, Miss. May Elizabeth': 1,
  'Warren, Mr. Charles William': 1,
  'Chisholm, Mr. Roderick Robert Crispin': 1,
  'Lyntakoff, Mr. Stanko': 1,
  'Portaluppi, Mr. Emilio Ilario Giuseppe': 1,
  'Klasen, Miss. Gertrud Emilia': 1,
  'Wells, Mrs. Arthur Henry (Addie" Dart Trevaskis)"': 1,
  'Nilsson, Mr. August Ferdinand': 1,
  'de Messemaeker, Mr. Guillaume Joseph': 1,
  'Midtsjo, Mr. Karl Albert': 1,
  'Bentham, Miss. Lilian W': 1,
  'Ford, Mr. Arthur': 1,
  'Mardirosian, Mr. Sarkis': 1,
  'Snyder, Mr. John Pillsbury': 1,
  'Franklin, Mr. Charles (Charles Fardon)': 1,
  'Dennis, Mr. William': 1,
  'Rosblom, Miss. Salli Helena': 1,
  'Touma, Miss. Maria Youssef': 1,
  'Fleming, Miss. Honora': 1,
  'Peacock, Master. Alfred Edward': 1,
  'Oreskovic, Miss. Jelka': 1,
  'Oxenham, Mr. Percy Thomas': 1,
  'Ware, Mr. John James': 1,
  'Faunthorpe, Mr. Harry': 1,
  'Parker, Mr. Clifford Richard': 1,
  'Bryhl, Miss. Dagmar Jenny Ingeborg ': 1,
  'Saade, Mr. Jean Nassr': 1,
  'Crosby, Mrs. Edward Gifford (Catherine Elizabeth Halstead)': 1,
  'McCarthy, Miss. Catherine Katie""': 1,
  'Pokrnic, Mr. Tome': 1,
  'Phillips, Mr. Escott Robert': 1,
  'Malachard, Mr. Noel': 1,
  'Olsson, Mr. Oscar Wilhelm': 1,
  'Johansson, Mr. Nils': 1,
  'Loring, Mr. Joseph Holland': 1,
  'Samaan, Mr. Hanna': 1,
  'Laroche, Miss. Louise': 1,
  'Angheloff, Mr. Minko': 1,
  'Wittevrongel, Mr. Camille': 1,
  'Dodge, Dr. Washington': 1,
  'Nasr, Mr. Mustafa': 1,
  'Daly, Miss. Margaret Marcella Maggie""': 1,
  'Rheims, Mr. George Alexander Lucien': 1,
  'Krekorian, Mr. Neshan': 1,
  'Andersson, Mr. Johan Samuel': 1,
  'Jefferys, Mr. Ernest Wilfred': 1,
  'Jonsson, Mr. Nils Hilding': 1,
  'Rogers, Mr. Reginald Harry': 1,
  'Spencer, Mr. William Augustus': 1,
  'Hagardon, Miss. Kate': 1,
  'White, Mrs. John Stuart (Ella Holmes)': 1,
  'Carr, Miss. Jeannie': 1,
  'Sadowitz, Mr. Harry': 1,
  'Vartanian, Mr. David': 1,
  'Cacic, Mr. Jego Grga': 1,
  'Hansen, Mrs. Claus Peter (Jennie L Howard)': 1,
  'Hays, Mr. Charles Melville': 1,
  'Aks, Master. Philip Frank': 1,
  'Allison, Mr. Hudson Joshua Creighton': 1,
  'Elias, Mr. Joseph': 1,
  'de Brito, Mr. Jose Joaquim': 1,
  'Maguire, Mr. John Edward': 1,
  'Cor, Mr. Ivan': 1,
  'Nakid, Mrs. Said (Waika Mary" Mowad)"': 1,
  'Thomas, Mr. Tannous': 1,
  'Dulles, Mr. William Crothers': 1,
  'Davies, Mrs. John Morgan (Elizabeth Agnes Mary White) ': 1,
  'Enander, Mr. Ingvar': 1,
  'Clarke, Mr. Charles Valentine': 1,
  'Rosenshine, Mr. George (Mr George Thorne")"': 1,
  'Becker, Miss. Ruth Elizabeth': 1,
  'Assam, Mr. Ali': 1,
  'Kreuchen, Miss. Emilie': 1,
  'Rowe, Mr. Alfred G': 1,
  'Nesson, Mr. Israel': 1,
  'Herman, Mr. Samuel': 1,
  'Dibden, Mr. William': 1,
  'Stokes, Mr. Philip Joseph': 1,
  'Greenfield, Mrs. Leo David (Blanche Strouse)': 1,
  'Walcroft, Miss. Nellie': 1,
  'Giles, Mr. Ralph': 1,
  'Whabee, Mrs. George Joseph (Shawneene Abi-Saab)': 1,
  'Botsford, Mr. William Hull': 1,
  'Abelseth, Miss. Karen Marie': 1,
  'van Billiard, Master. James William': 1,
  'Cardeza, Mrs. James Warburton Martinez (Charlotte Wardle Drake)': 1,
  'Sage, Mr. John George': 1,
  'Lundstrom, Mr. Thure Edvin': 1,
  'Fillbrook, Mr. Joseph Charles': 1,
  'Betros, Master. Seman': 1,
  'Denbury, Mr. Herbert': 1,
  'Pallas y Castello, Mr. Emilio': 1,
  'Gibson, Mrs. Leonard (Pauline C Boeson)': 1,
  'Riihivouri, Miss. Susanna Juhantytar Sanni""': 1,
  'Caram, Mr. Joseph': 1,
  'Sage, Mrs. John (Annie Bullen)': 1,
  'Harder, Mrs. George Achilles (Dorothy Annan)': 1,
  'Strilic, Mr. Ivan': 1,
  'Ware, Mrs. John James (Florence Louise Long)': 1,
  'Mallet, Mrs. Albert (Antoinette Magnin)': 1,
  'Sage, Master. William Henry': 1,
  'Lindell, Mrs. Edvard Bengtsson (Elin Gerda Persson)': 1,
  "O'Keefe, Mr. Patrick": 1,
  'Lockyer, Mr. Edward': 1,
  'Brown, Mrs. John Murray (Caroline Lane Lamson)': 1,
  'Julian, Mr. Henry Forbes': 1,
  'Dean, Miss. Elizabeth Gladys Millvina""': 1,
  'Herman, Miss. Kate': 1,
  'Wheeler, Mr. Edwin Frederick""': 1,
  "McNamee, Mrs. Neal (Eileen O'Leary)": 1,
  'Risien, Mrs. Samuel (Emma)': 1,
  'Foley, Mr. Joseph': 1,
  "O'Connor, Mr. Patrick": 1,
  'Asplund, Master. Carl Edgar': 1,
  'Hipkins, Mr. William Edward': 1,
  'Cotterill, Mr. Henry Harry""': 1,
  'Kink, Miss. Maria': 1,
  'Bowen, Miss. Grace Scott': 1,
  'Dodge, Mrs. Washington (Ruth Vidaver)': 1,
  'Harbeck, Mr. William H': 1,
  'Ismay, Mr. Joseph Bruce': 1,
  'Wilson, Miss. Helen Alice': 1,
  'Giles, Mr. Edgar': 1,
  'Wilkes, Mrs. James (Ellen Needs)': 1,
  'Ware, Mr. Frederick': 1,
  'Saether, Mr. Simon Sivertsen': 1,
  'Oliva y Ocana, Dona. Fermina': 1,
  'Spector, Mr. Woolf': 1,
  'Henriksson, Miss. Jenny Lovisa': 1,
  'Minahan, Mrs. William Edward (Lillian E Thorpe)': 1,
  'Naughton, Miss. Hannah': 1,
  'Peacock, Miss. Treasteall': 1,
  'Riordan, Miss. Johanna Hannah""': 1,
  'Widener, Mr. George Dunton': 1,
  'Ware, Mr. William Jeffery': 1,
  'Nourney, Mr. Alfred (Baron von Drachstedt")"': 1,
  'Frauenthal, Mr. Isaac Gerald': 1,
  'Carrau, Mr. Jose Pedro': 1,
  'Gibson, Miss. Dorothy Winifred': 1,
  'Assaf, Mr. Gerios': 1,
  'Keane, Mr. Daniel': 1,
  'del Carlo, Mrs. Sebastiano (Argenia Genovesi)': 1,
  'Chaffee, Mrs. Herbert Fuller (Carrie Constance Toogood)': 1,
  'Howard, Mr. Benjamin': 1,
  'Snyder, Mrs. John Pillsbury (Nelle Stevenson)': 1,
  'Jones, Mr. Charles Cresson': 1,
  'Ilieff, Mr. Ylio': 1,
  'Davies, Mr. John Samuel': 1,
  'Abrahim, Mrs. Joseph (Sophie Halaut Easu)': 1,
  'Caldwell, Mr. Albert Francis': 1,
  'Connolly, Miss. Kate': 1,
  'Svensson, Mr. Johan Cervin': 1,
  'Hirvonen, Mrs. Alexander (Helga E Lindqvist)': 1,
  'Wirz, Mr. Albert': 1,
  'Myles, Mr. Thomas Francis': 1},
 'Sex': {'male': 266, 'female': 152},
 'Embarked': {'S': 270, 'C': 102, 'Q': 46}}

In [34]:
encoder.transform(df)

     PassengerId  Name  Sex  Embarked
0            892     1  266        46
1            893     1  152       270
2            894     1  266        46
3            895     1  266       270
4            896     1  152       270
..           ...   ...  ...       ...
413         1305     1  266       270
414         1306     1  152       102
415         1307     1  266       270
416         1308     1  266       270
417         1309     1  266       102

[418 rows x 4 columns]

In [35]:
encoder = CountFrequencyEncoder(
    encoding_method='frequency',
    variables=['Name', 'Sex', 'Embarked'],
    ignore_format=True,
)

encoder.fit_transform(df)

     PassengerId      Name       Sex  Embarked
0            892  0.002392  0.636364  0.110048
1            893  0.002392  0.363636  0.645933
2            894  0.002392  0.636364  0.110048
3            895  0.002392  0.636364  0.645933
4            896  0.002392  0.363636  0.645933
..           ...       ...       ...       ...
413         1305  0.002392  0.636364  0.645933
414         1306  0.002392  0.363636  0.244019
415         1307  0.002392  0.636364  0.645933
416         1308  0.002392  0.636364  0.645933
417         1309  0.002392  0.636364  0.244019

[418 rows x 4 columns]