In [1]:
import pandas as pd

# 1. Load the data

In [27]:
df = pd.read_csv("../homeworks_2025_2026/pr_3/src/miss_titanic_surv_data.csv")

df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892.0,3.0,"Kelly, Mr. James",male,34.5,0.0,0.0,330911,7.8292,NaN,Q
1,893.0,3.0,NaN,female,47.0,1.0,0.0,363272,7.0000,NaN,NaN
2,894.0,2.0,"Myles, Mr. Thomas Francis",male,62.0,0.0,0.0,240276,9.6875,NaN,Q
3,895.0,3.0,"Wirz, Mr. Albert",male,27.0,0.0,0.0,315154,8.6625,NaN,NaN
4,896.0,3.0,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,NaN,1.0,NaN,3101298,12.2875,NaN,S

In [5]:
df.tail()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
95,987.0,3.0,"Tenglin, Mr. Gunnar Isidor",male,25.0,0.0,NaN,350033,NaN,NaN,S
96,988.0,NaN,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1.0,0.0,19877,NaN,C46,S
97,989.0,3.0,"Makinen, Mr. Kalle Edvard",male,29.0,NaN,0.0,STON/O 2. 3101268,7.9250,NaN,S
98,990.0,NaN,"Braf, Miss. Elin Ester Maria",female,20.0,0.0,0.0,347471,7.8542,NaN,S
99,991.0,3.0,"Nancarrow, Mr. William Henry",male,33.0,0.0,NaN,A./5. 3338,8.0500,NaN,S

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  90 non-null     float64
 1   Pclass       90 non-null     float64
 2   Name         90 non-null     object
 3   Sex          90 non-null     object
 4   Age          74 non-null     float64
 5   SibSp        90 non-null     float64
 6   Parch        90 non-null     float64
 7   Ticket       90 non-null     object
 8   Fare         90 non-null     float64
 9   Cabin        21 non-null     object
 10  Embarked     90 non-null     object
dtypes: float64(6), object(5)
memory usage: 8.7+ KB

# I. Strategy: fill the data

In [13]:
df.head(10)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892.0,3.0,"Kelly, Mr. James",male,34.5,0.0,0.0,330911,7.8292,NaN,Q
1,893.0,3.0,NaN,female,47.0,1.0,0.0,363272,7.0000,NaN,NaN
2,894.0,2.0,"Myles, Mr. Thomas Francis",male,62.0,0.0,0.0,240276,9.6875,NaN,Q
3,895.0,3.0,"Wirz, Mr. Albert",male,27.0,0.0,0.0,315154,8.6625,NaN,NaN
4,896.0,3.0,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,NaN,1.0,NaN,3101298,12.2875,NaN,S
5,897.0,3.0,"Svensson, Mr. Johan Cervin",male,14.0,0.0,0.0,7538,9.2250,NaN,S
6,NaN,3.0,"Connolly, Miss. Kate",NaN,30.0,0.0,0.0,330972,7.6292,NaN,Q
7,899.0,2.0,"Caldwell, Mr. Albert Francis",male,NaN,1.0,1.0,248738,29.0000,NaN,S
8,900.0,3.0,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0.0,0.0,2657,7.2292,NaN,C
9,901.0,3.0,"Davies, Mr. John Samuel",male,NaN,2.0,0.0,A/4 48871,24.1500,NaN,S

In [14]:
df_ff = df.ffill()

df_ff.head(10)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892.0,3.0,"Kelly, Mr. James",male,34.5,0.0,0.0,330911,7.8292,NaN,Q
1,893.0,3.0,"Kelly, Mr. James",female,47.0,1.0,0.0,363272,7.0000,NaN,Q
2,894.0,2.0,"Myles, Mr. Thomas Francis",male,62.0,0.0,0.0,240276,9.6875,NaN,Q
3,895.0,3.0,"Wirz, Mr. Albert",male,27.0,0.0,0.0,315154,8.6625,NaN,Q
4,896.0,3.0,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,27.0,1.0,0.0,3101298,12.2875,NaN,S
5,897.0,3.0,"Svensson, Mr. Johan Cervin",male,14.0,0.0,0.0,7538,9.2250,NaN,S
6,897.0,3.0,"Connolly, Miss. Kate",male,30.0,0.0,0.0,330972,7.6292,NaN,Q
7,899.0,2.0,"Caldwell, Mr. Albert Francis",male,30.0,1.0,1.0,248738,29.0000,NaN,S
8,900.0,3.0,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0.0,0.0,2657,7.2292,NaN,C
9,901.0,3.0,"Davies, Mr. John Samuel",male,18.0,2.0,0.0,A/4 48871,24.1500,NaN,S

In [15]:
df.tail(10)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
90,982.0,3.0,"Dyker, Mrs. Adolf Fredrik (Anna Elisabeth Judi...",female,22.0,1.0,0.0,347072,13.9000,NaN,S
91,983.0,3.0,"Pedersen, Mr. Olaf",NaN,NaN,0.0,0.0,NaN,7.7750,NaN,S
92,984.0,1.0,"Davidson, Mrs. Thornton (Orian Hays)",female,27.0,NaN,2.0,F.C. 12750,52.0000,B71,S
93,985.0,3.0,NaN,male,NaN,0.0,0.0,376563,8.0500,NaN,S
94,986.0,1.0,"Birnbaum, Mr. Jakob",male,25.0,NaN,0.0,13905,26.0000,NaN,C
95,987.0,3.0,"Tenglin, Mr. Gunnar Isidor",male,25.0,0.0,NaN,350033,NaN,NaN,S
96,988.0,NaN,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1.0,0.0,19877,NaN,C46,S
97,989.0,3.0,"Makinen, Mr. Kalle Edvard",male,29.0,NaN,0.0,STON/O 2. 3101268,7.9250,NaN,S
98,990.0,NaN,"Braf, Miss. Elin Ester Maria",female,20.0,0.0,0.0,347471,7.8542,NaN,S
99,991.0,3.0,"Nancarrow, Mr. William Henry",male,33.0,0.0,NaN,A./5. 3338,8.0500,NaN,S

In [16]:
df_ff.tail(10)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
90,982.0,3.0,"Dyker, Mrs. Adolf Fredrik (Anna Elisabeth Judi...",female,22.0,1.0,0.0,347072,13.9000,C55 C57,S
91,983.0,3.0,"Pedersen, Mr. Olaf",female,22.0,0.0,0.0,347072,7.7750,C55 C57,S
92,984.0,1.0,"Davidson, Mrs. Thornton (Orian Hays)",female,27.0,0.0,2.0,F.C. 12750,52.0000,B71,S
93,985.0,3.0,"Davidson, Mrs. Thornton (Orian Hays)",male,27.0,0.0,0.0,376563,8.0500,B71,S
94,986.0,1.0,"Birnbaum, Mr. Jakob",male,25.0,0.0,0.0,13905,26.0000,B71,C
95,987.0,3.0,"Tenglin, Mr. Gunnar Isidor",male,25.0,0.0,0.0,350033,26.0000,B71,S
96,988.0,3.0,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1.0,0.0,19877,26.0000,C46,S
97,989.0,3.0,"Makinen, Mr. Kalle Edvard",male,29.0,1.0,0.0,STON/O 2. 3101268,7.9250,C46,S
98,990.0,3.0,"Braf, Miss. Elin Ester Maria",female,20.0,0.0,0.0,347471,7.8542,C46,S
99,991.0,3.0,"Nancarrow, Mr. William Henry",male,33.0,0.0,0.0,A./5. 3338,8.0500,C46,S

In [17]:
df_ff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  100 non-null    float64
 1   Pclass       100 non-null    float64
 2   Name         100 non-null    object
 3   Sex          100 non-null    object
 4   Age          100 non-null    float64
 5   SibSp        100 non-null    float64
 6   Parch        100 non-null    float64
 7   Ticket       100 non-null    object
 8   Fare         100 non-null    float64
 9   Cabin        88 non-null     object
 10  Embarked     100 non-null    object
dtypes: float64(6), object(5)
memory usage: 8.7+ KB

In [18]:
df_bf = df.bfill()

df_bf.head(10)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892.0,3.0,"Kelly, Mr. James",male,34.5,0.0,0.0,330911,7.8292,B45,Q
1,893.0,3.0,"Myles, Mr. Thomas Francis",female,47.0,1.0,0.0,363272,7.0000,B45,Q
2,894.0,2.0,"Myles, Mr. Thomas Francis",male,62.0,0.0,0.0,240276,9.6875,B45,Q
3,895.0,3.0,"Wirz, Mr. Albert",male,27.0,0.0,0.0,315154,8.6625,B45,S
4,896.0,3.0,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,14.0,1.0,0.0,3101298,12.2875,B45,S
5,897.0,3.0,"Svensson, Mr. Johan Cervin",male,14.0,0.0,0.0,7538,9.2250,B45,S
6,899.0,3.0,"Connolly, Miss. Kate",male,30.0,0.0,0.0,330972,7.6292,B45,Q
7,899.0,2.0,"Caldwell, Mr. Albert Francis",male,18.0,1.0,1.0,248738,29.0000,B45,S
8,900.0,3.0,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0.0,0.0,2657,7.2292,B45,C
9,901.0,3.0,"Davies, Mr. John Samuel",male,46.0,2.0,0.0,A/4 48871,24.1500,B45,S

In [19]:
df_bf.tail(10)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
90,982.0,3.0,"Dyker, Mrs. Adolf Fredrik (Anna Elisabeth Judi...",female,22.0,1.0,0.0,347072,13.9000,B71,S
91,983.0,3.0,"Pedersen, Mr. Olaf",female,27.0,0.0,0.0,F.C. 12750,7.7750,B71,S
92,984.0,1.0,"Davidson, Mrs. Thornton (Orian Hays)",female,27.0,0.0,2.0,F.C. 12750,52.0000,B71,S
93,985.0,3.0,"Birnbaum, Mr. Jakob",male,25.0,0.0,0.0,376563,8.0500,C46,S
94,986.0,1.0,"Birnbaum, Mr. Jakob",male,25.0,0.0,0.0,13905,26.0000,C46,C
95,987.0,3.0,"Tenglin, Mr. Gunnar Isidor",male,25.0,0.0,0.0,350033,7.9250,C46,S
96,988.0,3.0,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1.0,0.0,19877,7.9250,C46,S
97,989.0,3.0,"Makinen, Mr. Kalle Edvard",male,29.0,0.0,0.0,STON/O 2. 3101268,7.9250,NaN,S
98,990.0,3.0,"Braf, Miss. Elin Ester Maria",female,20.0,0.0,0.0,347471,7.8542,NaN,S
99,991.0,3.0,"Nancarrow, Mr. William Henry",male,33.0,0.0,NaN,A./5. 3338,8.0500,NaN,S

In [21]:
df_copy = df.copy(deep=True)
df_copy.head(10)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892.0,3.0,"Kelly, Mr. James",male,34.5,0.0,0.0,330911,7.8292,NaN,Q
1,893.0,3.0,NaN,female,47.0,1.0,0.0,363272,7.0000,NaN,NaN
2,894.0,2.0,"Myles, Mr. Thomas Francis",male,62.0,0.0,0.0,240276,9.6875,NaN,Q
3,895.0,3.0,"Wirz, Mr. Albert",male,27.0,0.0,0.0,315154,8.6625,NaN,NaN
4,896.0,3.0,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,NaN,1.0,NaN,3101298,12.2875,NaN,S
5,897.0,3.0,"Svensson, Mr. Johan Cervin",male,14.0,0.0,0.0,7538,9.2250,NaN,S
6,NaN,3.0,"Connolly, Miss. Kate",NaN,30.0,0.0,0.0,330972,7.6292,NaN,Q
7,899.0,2.0,"Caldwell, Mr. Albert Francis",male,NaN,1.0,1.0,248738,29.0000,NaN,S
8,900.0,3.0,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0.0,0.0,2657,7.2292,NaN,C
9,901.0,3.0,"Davies, Mr. John Samuel",male,NaN,2.0,0.0,A/4 48871,24.1500,NaN,S

In [22]:
df_copy["PassengerId"] = df["PassengerId"].fillna(-1)
df_copy.head(10)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892.0,3.0,"Kelly, Mr. James",male,34.5,0.0,0.0,330911,7.8292,NaN,Q
1,893.0,3.0,NaN,female,47.0,1.0,0.0,363272,7.0000,NaN,NaN
2,894.0,2.0,"Myles, Mr. Thomas Francis",male,62.0,0.0,0.0,240276,9.6875,NaN,Q
3,895.0,3.0,"Wirz, Mr. Albert",male,27.0,0.0,0.0,315154,8.6625,NaN,NaN
4,896.0,3.0,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,NaN,1.0,NaN,3101298,12.2875,NaN,S
5,897.0,3.0,"Svensson, Mr. Johan Cervin",male,14.0,0.0,0.0,7538,9.2250,NaN,S
6,-1.0,3.0,"Connolly, Miss. Kate",NaN,30.0,0.0,0.0,330972,7.6292,NaN,Q
7,899.0,2.0,"Caldwell, Mr. Albert Francis",male,NaN,1.0,1.0,248738,29.0000,NaN,S
8,900.0,3.0,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0.0,0.0,2657,7.2292,NaN,C
9,901.0,3.0,"Davies, Mr. John Samuel",male,NaN,2.0,0.0,A/4 48871,24.1500,NaN,S

In [23]:
df_copy.tail(10)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
90,982.0,3.0,"Dyker, Mrs. Adolf Fredrik (Anna Elisabeth Judi...",female,22.0,1.0,0.0,347072,13.9000,NaN,S
91,983.0,3.0,"Pedersen, Mr. Olaf",NaN,NaN,0.0,0.0,NaN,7.7750,NaN,S
92,984.0,1.0,"Davidson, Mrs. Thornton (Orian Hays)",female,27.0,NaN,2.0,F.C. 12750,52.0000,B71,S
93,985.0,3.0,NaN,male,NaN,0.0,0.0,376563,8.0500,NaN,S
94,986.0,1.0,"Birnbaum, Mr. Jakob",male,25.0,NaN,0.0,13905,26.0000,NaN,C
95,987.0,3.0,"Tenglin, Mr. Gunnar Isidor",male,25.0,0.0,NaN,350033,NaN,NaN,S
96,988.0,NaN,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1.0,0.0,19877,NaN,C46,S
97,989.0,3.0,"Makinen, Mr. Kalle Edvard",male,29.0,NaN,0.0,STON/O 2. 3101268,7.9250,NaN,S
98,990.0,NaN,"Braf, Miss. Elin Ester Maria",female,20.0,0.0,0.0,347471,7.8542,NaN,S
99,991.0,3.0,"Nancarrow, Mr. William Henry",male,33.0,0.0,NaN,A./5. 3338,8.0500,NaN,S

In [24]:
numeric_cols = df_copy.select_dtypes(include=['number']).columns
numeric_cols

Index(['PassengerId', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [28]:
df_copy[numeric_cols] = df_copy[numeric_cols].fillna(-10)
df_copy.head(10)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892.0,3.0,"Kelly, Mr. James",male,34.5,0.0,0.0,330911,7.8292,NaN,Q
1,893.0,3.0,NaN,female,47.0,1.0,0.0,363272,7.0000,NaN,NaN
2,894.0,2.0,"Myles, Mr. Thomas Francis",male,62.0,0.0,0.0,240276,9.6875,NaN,Q
3,895.0,3.0,"Wirz, Mr. Albert",male,27.0,0.0,0.0,315154,8.6625,NaN,NaN
4,896.0,3.0,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,-10.0,1.0,-10.0,3101298,12.2875,NaN,S
5,897.0,3.0,"Svensson, Mr. Johan Cervin",male,14.0,0.0,0.0,7538,9.2250,NaN,S
6,-1.0,3.0,"Connolly, Miss. Kate",NaN,30.0,0.0,0.0,330972,7.6292,NaN,Q
7,899.0,2.0,"Caldwell, Mr. Albert Francis",male,-10.0,1.0,1.0,248738,29.0000,NaN,S
8,900.0,3.0,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0.0,0.0,2657,7.2292,NaN,C
9,901.0,3.0,"Davies, Mr. John Samuel",male,-10.0,2.0,0.0,A/4 48871,24.1500,NaN,S

In [29]:
df_copy.tail(10)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
90,982.0,3.0,"Dyker, Mrs. Adolf Fredrik (Anna Elisabeth Judi...",female,22.0,1.0,0.0,347072,13.9000,NaN,S
91,983.0,3.0,"Pedersen, Mr. Olaf",NaN,-10.0,0.0,0.0,NaN,7.7750,NaN,S
92,984.0,1.0,"Davidson, Mrs. Thornton (Orian Hays)",female,27.0,-10.0,2.0,F.C. 12750,52.0000,B71,S
93,985.0,3.0,NaN,male,-10.0,0.0,0.0,376563,8.0500,NaN,S
94,986.0,1.0,"Birnbaum, Mr. Jakob",male,25.0,-10.0,0.0,13905,26.0000,NaN,C
95,987.0,3.0,"Tenglin, Mr. Gunnar Isidor",male,25.0,0.0,-10.0,350033,-10.0000,NaN,S
96,988.0,-10.0,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1.0,0.0,19877,-10.0000,C46,S
97,989.0,3.0,"Makinen, Mr. Kalle Edvard",male,29.0,-10.0,0.0,STON/O 2. 3101268,7.9250,NaN,S
98,990.0,-10.0,"Braf, Miss. Elin Ester Maria",female,20.0,0.0,0.0,347471,7.8542,NaN,S
99,991.0,3.0,"Nancarrow, Mr. William Henry",male,33.0,0.0,-10.0,A./5. 3338,8.0500,NaN,S

In [31]:
df_copy["Name"] = df_copy["Name"].fillna("Unmentioned")

In [32]:
df_copy.head(10)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892.0,3.0,"Kelly, Mr. James",male,34.5,0.0,0.0,330911,7.8292,NaN,Q
1,893.0,3.0,Unmentioned,female,47.0,1.0,0.0,363272,7.0000,NaN,NaN
2,894.0,2.0,"Myles, Mr. Thomas Francis",male,62.0,0.0,0.0,240276,9.6875,NaN,Q
3,895.0,3.0,"Wirz, Mr. Albert",male,27.0,0.0,0.0,315154,8.6625,NaN,NaN
4,896.0,3.0,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,-10.0,1.0,-10.0,3101298,12.2875,NaN,S
5,897.0,3.0,"Svensson, Mr. Johan Cervin",male,14.0,0.0,0.0,7538,9.2250,NaN,S
6,-1.0,3.0,"Connolly, Miss. Kate",NaN,30.0,0.0,0.0,330972,7.6292,NaN,Q
7,899.0,2.0,"Caldwell, Mr. Albert Francis",male,-10.0,1.0,1.0,248738,29.0000,NaN,S
8,900.0,3.0,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0.0,0.0,2657,7.2292,NaN,C
9,901.0,3.0,"Davies, Mr. John Samuel",male,-10.0,2.0,0.0,A/4 48871,24.1500,NaN,S

In [33]:
df_copy.tail(10)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
90,982.0,3.0,"Dyker, Mrs. Adolf Fredrik (Anna Elisabeth Judi...",female,22.0,1.0,0.0,347072,13.9000,NaN,S
91,983.0,3.0,"Pedersen, Mr. Olaf",NaN,-10.0,0.0,0.0,NaN,7.7750,NaN,S
92,984.0,1.0,"Davidson, Mrs. Thornton (Orian Hays)",female,27.0,-10.0,2.0,F.C. 12750,52.0000,B71,S
93,985.0,3.0,Unmentioned,male,-10.0,0.0,0.0,376563,8.0500,NaN,S
94,986.0,1.0,"Birnbaum, Mr. Jakob",male,25.0,-10.0,0.0,13905,26.0000,NaN,C
95,987.0,3.0,"Tenglin, Mr. Gunnar Isidor",male,25.0,0.0,-10.0,350033,-10.0000,NaN,S
96,988.0,-10.0,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1.0,0.0,19877,-10.0000,C46,S
97,989.0,3.0,"Makinen, Mr. Kalle Edvard",male,29.0,-10.0,0.0,STON/O 2. 3101268,7.9250,NaN,S
98,990.0,-10.0,"Braf, Miss. Elin Ester Maria",female,20.0,0.0,0.0,347471,7.8542,NaN,S
99,991.0,3.0,"Nancarrow, Mr. William Henry",male,33.0,0.0,-10.0,A./5. 3338,8.0500,NaN,S

In [34]:
obj_cols = df_copy.select_dtypes(include=['object']).columns
obj_cols

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [35]:
df_copy[obj_cols] = df_copy[obj_cols].fillna("MISSED")
df_copy.head(10)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892.0,3.0,"Kelly, Mr. James",male,34.5,0.0,0.0,330911,7.8292,MISSED,Q
1,893.0,3.0,Unmentioned,female,47.0,1.0,0.0,363272,7.0000,MISSED,MISSED
2,894.0,2.0,"Myles, Mr. Thomas Francis",male,62.0,0.0,0.0,240276,9.6875,MISSED,Q
3,895.0,3.0,"Wirz, Mr. Albert",male,27.0,0.0,0.0,315154,8.6625,MISSED,MISSED
4,896.0,3.0,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,-10.0,1.0,-10.0,3101298,12.2875,MISSED,S
5,897.0,3.0,"Svensson, Mr. Johan Cervin",male,14.0,0.0,0.0,7538,9.2250,MISSED,S
6,-1.0,3.0,"Connolly, Miss. Kate",MISSED,30.0,0.0,0.0,330972,7.6292,MISSED,Q
7,899.0,2.0,"Caldwell, Mr. Albert Francis",male,-10.0,1.0,1.0,248738,29.0000,MISSED,S
8,900.0,3.0,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0.0,0.0,2657,7.2292,MISSED,C
9,901.0,3.0,"Davies, Mr. John Samuel",male,-10.0,2.0,0.0,A/4 48871,24.1500,MISSED,S

In [ ]:
# Suppose we have a DataFrame with numeric (or object values only)
# df.fillna(-300, inplace=True)

In [37]:
df_copy = df.copy(deep=True)
df_copy.head(10)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892.0,3.0,"Kelly, Mr. James",male,34.5,0.0,0.0,330911,7.8292,NaN,Q
1,893.0,3.0,NaN,female,47.0,1.0,0.0,363272,7.0000,NaN,NaN
2,894.0,2.0,"Myles, Mr. Thomas Francis",male,62.0,0.0,0.0,240276,9.6875,NaN,Q
3,895.0,3.0,"Wirz, Mr. Albert",male,27.0,0.0,0.0,315154,8.6625,NaN,NaN
4,896.0,3.0,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,NaN,1.0,NaN,3101298,12.2875,NaN,S
5,897.0,3.0,"Svensson, Mr. Johan Cervin",male,14.0,0.0,0.0,7538,9.2250,NaN,S
6,NaN,3.0,"Connolly, Miss. Kate",NaN,30.0,0.0,0.0,330972,7.6292,NaN,Q
7,899.0,2.0,"Caldwell, Mr. Albert Francis",male,NaN,1.0,1.0,248738,29.0000,NaN,S
8,900.0,3.0,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0.0,0.0,2657,7.2292,NaN,C
9,901.0,3.0,"Davies, Mr. John Samuel",male,NaN,2.0,0.0,A/4 48871,24.1500,NaN,S

In [38]:
# 2. Fill 'Female' for missing rows where Name contains "Miss" or "Mrs."
df_copy.loc[df_copy['Sex'].isna() & df_copy['Name'].str.contains('Miss|Mrs\.', regex=True), 'Sex'] = 'FEMALE'

# 3. Fill 'Male' for missing rows where Name contains "Mr."
df_copy.loc[df_copy['Sex'].isna() & df_copy['Name'].str.contains('Mr\.', regex=True), 'Sex'] = 'MALE'

In [40]:
df_copy.head(10)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892.0,3.0,"Kelly, Mr. James",male,34.5,0.0,0.0,330911,7.8292,NaN,Q
1,893.0,3.0,NaN,female,47.0,1.0,0.0,363272,7.0000,NaN,NaN
2,894.0,2.0,"Myles, Mr. Thomas Francis",male,62.0,0.0,0.0,240276,9.6875,NaN,Q
3,895.0,3.0,"Wirz, Mr. Albert",male,27.0,0.0,0.0,315154,8.6625,NaN,NaN
4,896.0,3.0,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,NaN,1.0,NaN,3101298,12.2875,NaN,S
5,897.0,3.0,"Svensson, Mr. Johan Cervin",male,14.0,0.0,0.0,7538,9.2250,NaN,S
6,NaN,3.0,"Connolly, Miss. Kate",FEMALE,30.0,0.0,0.0,330972,7.6292,NaN,Q
7,899.0,2.0,"Caldwell, Mr. Albert Francis",male,NaN,1.0,1.0,248738,29.0000,NaN,S
8,900.0,3.0,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0.0,0.0,2657,7.2292,NaN,C
9,901.0,3.0,"Davies, Mr. John Samuel",male,NaN,2.0,0.0,A/4 48871,24.1500,NaN,S

In [41]:
df_copy.to_csv("./src/filled_sex_by_name.csv", index=False)

# II strategy: removing columns or rows by missing values statistics

In [42]:
df_copy = df.copy(deep=True)

In [44]:
missing_percentage = (df_copy.isna().mean() * 100).round(2)
missing_percentage

PassengerId    10.0
Pclass         10.0
Name           10.0
Sex            10.0
Age            26.0
SibSp          10.0
Parch          10.0
Ticket         10.0
Fare           10.0
Cabin          79.0
Embarked       10.0
dtype: float64

In [48]:
threshold = 50   # in practice, it could be more than 95%
                 # 97-99%
missing_percentage = missing_percentage[missing_percentage > threshold]
missing_percentage

Cabin    79.0
dtype: float64

In [50]:
list(missing_percentage.index)

['Cabin']

In [51]:
df_copy.drop(columns=list(missing_percentage.index), inplace=True)
df_copy.head(10)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892.0,3.0,"Kelly, Mr. James",male,34.5,0.0,0.0,330911,7.8292,Q
1,893.0,3.0,NaN,female,47.0,1.0,0.0,363272,7.0000,NaN
2,894.0,2.0,"Myles, Mr. Thomas Francis",male,62.0,0.0,0.0,240276,9.6875,Q
3,895.0,3.0,"Wirz, Mr. Albert",male,27.0,0.0,0.0,315154,8.6625,NaN
4,896.0,3.0,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,NaN,1.0,NaN,3101298,12.2875,S
5,897.0,3.0,"Svensson, Mr. Johan Cervin",male,14.0,0.0,0.0,7538,9.2250,S
6,NaN,3.0,"Connolly, Miss. Kate",NaN,30.0,0.0,0.0,330972,7.6292,Q
7,899.0,2.0,"Caldwell, Mr. Albert Francis",male,NaN,1.0,1.0,248738,29.0000,S
8,900.0,3.0,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0.0,0.0,2657,7.2292,C
9,901.0,3.0,"Davies, Mr. John Samuel",male,NaN,2.0,0.0,A/4 48871,24.1500,S

In [52]:
missing_percentage = (df_copy.isna().mean() * 100).round(2)
missing_percentage

PassengerId    10.0
Pclass         10.0
Name           10.0
Sex            10.0
Age            26.0
SibSp          10.0
Parch          10.0
Ticket         10.0
Fare           10.0
Embarked       10.0
dtype: float64

In [53]:
df_copy.shape

(100, 10)

In [55]:
df_copy = df_copy.dropna(subset=['Name'])
df_copy.head(10)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892.0,3.0,"Kelly, Mr. James",male,34.5,0.0,0.0,330911,7.8292,Q
2,894.0,2.0,"Myles, Mr. Thomas Francis",male,62.0,0.0,0.0,240276,9.6875,Q
3,895.0,3.0,"Wirz, Mr. Albert",male,27.0,0.0,0.0,315154,8.6625,NaN
4,896.0,3.0,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,NaN,1.0,NaN,3101298,12.2875,S
5,897.0,3.0,"Svensson, Mr. Johan Cervin",male,14.0,0.0,0.0,7538,9.2250,S
6,NaN,3.0,"Connolly, Miss. Kate",NaN,30.0,0.0,0.0,330972,7.6292,Q
7,899.0,2.0,"Caldwell, Mr. Albert Francis",male,NaN,1.0,1.0,248738,29.0000,S
8,900.0,3.0,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0.0,0.0,2657,7.2292,C
9,901.0,3.0,"Davies, Mr. John Samuel",male,NaN,2.0,0.0,A/4 48871,24.1500,S
10,902.0,3.0,"Ilieff, Mr. Ylio",male,NaN,0.0,0.0,349220,7.8958,S

In [56]:
df_copy.shape

(90, 10)

In [57]:
missing_percentage = (df_copy.isna().mean() * 100).round(2)
missing_percentage

PassengerId    11.11
Pclass         11.11
Name            0.00
Sex            10.00
Age            24.44
SibSp          11.11
Parch          10.00
Ticket         11.11
Fare           11.11
Embarked        7.78
dtype: float64

In [58]:
df_copy.dropna(inplace=True)
df_copy.shape

(30, 10)

In [60]:
df_copy.head(10)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892.0,3.0,"Kelly, Mr. James",male,34.5,0.0,0.0,330911,7.8292,Q
2,894.0,2.0,"Myles, Mr. Thomas Francis",male,62.0,0.0,0.0,240276,9.6875,Q
5,897.0,3.0,"Svensson, Mr. Johan Cervin",male,14.0,0.0,0.0,7538,9.2250,S
8,900.0,3.0,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0.0,0.0,2657,7.2292,C
13,905.0,2.0,"Howard, Mr. Benjamin",male,63.0,1.0,0.0,24065,26.0000,S
15,907.0,2.0,"del Carlo, Mrs. Sebastiano (Argenia Genovesi)",female,24.0,1.0,0.0,SC/PARIS 2167,27.7208,C
16,908.0,2.0,"Keane, Mr. Daniel",male,35.0,0.0,0.0,233734,12.3500,Q
18,910.0,3.0,"Ilmakangas, Miss. Ida Livija",female,27.0,1.0,0.0,STON/O2. 3101270,7.9250,S
21,913.0,3.0,"Olsen, Master. Artur Karl",male,9.0,0.0,1.0,C 17368,3.1708,S
26,918.0,1.0,"Ostby, Miss. Helene Ragnhild",female,22.0,0.0,1.0,113509,61.9792,C

In [61]:
missing_percentage = (df_copy.isna().mean() * 100).round(2)
missing_percentage

PassengerId    0.0
Pclass         0.0
Name           0.0
Sex            0.0
Age            0.0
SibSp          0.0
Parch          0.0
Ticket         0.0
Fare           0.0
Embarked       0.0
dtype: float64